version: 2

jobs:
  magento21:
    docker:
      - image: rafaelcgstz/magento2
      
    steps:
      - checkout
      - run:
          name: Install Magento
          command: 'install-magento2'
  magento22:
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout 

workflows:
  version: 2

  my_workflows:
    jobs:
      - magento21
      - magento22