version: 2

jobs:
  magento21:
    docker:
      - image: rafaelcgstz/magento2
      
    steps:
      - checkout
      - run:
          name: Install Magento
          command: 'curl -s https://raw.githubusercontent.com/clean-docker/Magento2/master/init | bash -s MYMAGENTO2 clone'
      - run:
          name: Install Magento
          command: 'cd MYMAGENTO2 && install-magento2'
  magento22:
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout 

workflows:
  version: 2

  my_workflows:
    jobs:
      - magento21
      - magento22