version: 2

jobs:
  magento21:
    docker:
      - image: rafaelcgstz/magento2
      
    steps:
      - checkout
      
  magento22:
    docker:
      - image: rafaelcgstz/magento2
    steps:
      - checkout 
      - run:
        name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-c
      - run:
        name: Image up
          command: |
            docker-compose up -d

workflows:
  version: 2

  my_workflows:
    jobs:
      - magento21
      - magento22