version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4.0
    branches:
      only:
        - circleci
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start container and verify it's working
          command: docker-compose up --d